# -*- coding: utf-8 -*-
"""UI texts (extracted from laptop_ui.py)."""

from __future__ import annotations

import copy


_UI_TEXTS = {
    "zh_cn": {
        "window_title": "FOCUST 食源性致病菌时序自动化训练检测系统",
        "mode_title": "模式选择",
        "single_mode": "文件夹分析",
        "batch_mode": "数据集评估",
        "lang_title": "语言",
        "lang_cn": "中文",
        "lang_en": "English",
        "path_title": "路径设置",
        "select_folder": "选择图片文件夹...",
        "select_folders": "选择多个文件夹...",
        "select_dataset": "选择数据集根目录...",
        "output_path_label": "输出目录:",
        "select_output_path": "选择...",
        "select_output_path_tooltip": "设置输出目录（写入配置覆盖文件，CLI 同样生效）",
        "output_by_run": "按运行分目录保存（推荐）",
        "output_by_run_tooltip": "启用后每次运行会在输出目录下创建 gui_run_YYYYMMDD_HHMMSS 子目录，把本次运行输出放一起。",
        "auto_save_results": "自动保存结果（PNG+CSV）",
        "auto_save_results_tooltip": "成功完成后自动保存当前预览结果到输出目录",
        "open_output_on_finish": "完成后打开输出目录",
        "open_output_on_finish_tooltip": "成功完成后自动打开输出目录（或本次运行目录）",
        "engine_hint_hcp": "HCP：候选检测 →（可选）二分类过滤 →（可选）多分类识别。",
        "engine_hint_hcp_yolo": "HCP-YOLO：需要 YOLO .pt + ultralytics；可选加载多分类 .pth 做细化（更慢更准）。",
        "models_title": "模型加载",
        "load_binary": "加载二分类模型...",
        "load_multiclass": "加载多分类模型...",
        "binary_model_status": "二分类模型:",
        "multiclass_model_status": "多分类模型:",
        "not_loaded": "未加载",
        "process_title": "处理控制",
        "start": "开始处理",
        "stop": "停止处理",
        "save": "保存结果",
        "start_eval": "开始评估",
        "results_title": "结果预览",
        "log_title": "日志",
        "status_ready": "准备就绪",
        "status_stopped": "处理已停止。",
        "status_done": "处理成功完成！",
        "status_failed": "处理失败。",
        "warn_no_path_title": "警告",
        "warn_no_path_msg": "请先选择一个有效的文件夹或数据集目录。",
        "save_result_title": "保存结果",
        "save_success_title": "保存成功",
        "save_success_msg": "结果已成功保存至:\n{}",
        "save_fail_title": "保存失败",
        "save_fail_msg": "保存结果时出错: {}",
        "no_result_to_save": "没有可供保存的结果。",
        "exit_confirm_title": "确认退出",
        "exit_confirm_msg": "您确定要退出程序吗？",
        "preview_placeholder": "请先处理图像以预览结果",
        "eval_settings_title": "评估设置",
        "iou_threshold_label": "IoU 匹配阈值(可视化):",
        "dataset_parse_fail": "数据集解析失败: {e}",
        "dataset_parse_success": "成功解析 {count} 个序列，准备评估。",
        "dataset_parsing": "正在解析数据集，请稍候...",
        "dataset_no_sequences": "数据集中未找到有效序列。",
        "folder_list_title": "选中的文件夹列表",
        "clear_folders": "清空列表",
        "remove_selected": "移除选中",
        "remove_selected_tooltip": "从列表中移除选中的文件夹（不会删除磁盘文件）",
        "folder_list_tooltip": "支持拖拽文件夹到此处。\n双击打开文件夹；Delete 键移除选中项。",
        "folders_selected": "已选择 {count} 个文件夹",
        "perform_iou_sweep_checkbox": "执行IoU扫描评估 (0.05-0.95)",
        "micro_batch_mode": "微批次模式",
        "micro_batch_size_label": "批次大小:",
        "micro_batch_tooltip": "启用后分块处理标注框，降低CPU/GPU内存压力（如出现 DefaultCPUAllocator not enough memory 请减小批次）",
        "micro_batch_size_tooltip": "每次处理的标注框数量（越小越省内存，越大越快）",
        "dual_mode_eval_tooltip": "启用双模式评估：分别运行启用和禁用小菌落过滤，生成对比报告",
        "fit_view": "适应窗口",
        "zoom_100": "100%",
        "show_labels": "显示标签",
        "show_confidence": "显示置信度",
        "highlight_label": "高亮:",
        "open_output_folder": "打开输出目录",
        "copy_log": "复制日志",
        "clear_log": "清空日志",
        "help": "帮助",
        "help_tooltip": "打开快速帮助（F1）",
    },
    "en_us": {
        "window_title": "FOCUST: Foodborne Pathogen Temporal Automated Training Detection System",
        "mode_title": "Mode Selection",
        "single_mode": "Folder Analysis",
        "batch_mode": "Dataset Evaluation",
        "lang_title": "Language",
        "lang_cn": "中文",
        "lang_en": "English",
        "path_title": "Path Settings",
        "select_folder": "Select Image Folder...",
        "select_folders": "Select Multiple Folders...",
        "select_dataset": "Select Dataset Root...",
        "output_path_label": "Output:",
        "select_output_path": "Browse...",
        "select_output_path_tooltip": "Set output directory (saved to config override; affects CLI too).",
        "output_by_run": "Organize outputs by run (recommended)",
        "output_by_run_tooltip": "Create a gui_run_YYYYMMDD_HHMMSS subfolder per run to keep outputs together.",
        "auto_save_results": "Auto-save results (PNG+CSV)",
        "auto_save_results_tooltip": "Automatically save the annotated preview and CSV to the output folder on success.",
        "open_output_on_finish": "Open output on finish",
        "open_output_on_finish_tooltip": "Open the output (or run) folder after successful completion.",
        "engine_hint_hcp": "HCP: proposals → (optional) binary filter → (optional) multi-class classification.",
        "engine_hint_hcp_yolo": "HCP-YOLO: requires YOLO .pt + ultralytics; optional .pth refinement (slower, more accurate).",
        "models_title": "Model Loading",
        "load_binary": "Load Binary Classifier...",
        "load_multiclass": "Load Multi-Class Classifier...",
        "binary_model_status": "Binary Model:",
        "multiclass_model_status": "Multi-Class Model:",
        "not_loaded": "Not Loaded",
        "process_title": "Processing Control",
        "start": "Start Processing",
        "stop": "Stop Processing",
        "save": "Save Results",
        "start_eval": "Start Evaluation",
        "results_title": "Result Preview",
        "log_title": "Log",
        "status_ready": "Ready",
        "status_stopped": "Processing stopped.",
        "status_done": "Processing completed successfully!",
        "status_failed": "Processing failed.",
        "warn_no_path_title": "Warning",
        "warn_no_path_msg": "Please select a valid folder or dataset directory first.",
        "save_result_title": "Save Results",
        "save_success_title": "Save Successful",
        "save_success_msg": "Results have been saved to:\n{}",
        "save_fail_title": "Save Failed",
        "save_fail_msg": "Error saving results: {}",
        "no_result_to_save": "No results available to save.",
        "exit_confirm_title": "Confirm Exit",
        "exit_confirm_msg": "Are you sure you want to exit the application?",
        "preview_placeholder": "Process an image to see the result preview",
        "eval_settings_title": "Evaluation Settings",
        "iou_threshold_label": "IoU Match Threshold (for Viz):",
        "dataset_parse_fail": "Failed to parse dataset: {e}",
        "dataset_parse_success": "Successfully parsed {count} sequences. Ready for evaluation.",
        "dataset_parsing": "Parsing dataset, please wait...",
        "dataset_no_sequences": "No valid sequences found in the dataset.",
        "folder_list_title": "Selected Folders List",
        "clear_folders": "Clear List",
        "remove_selected": "Remove selected",
        "remove_selected_tooltip": "Remove selected folders from the list (does not delete files).",
        "folder_list_tooltip": "Drag & drop folders here.\nDouble-click to open; press Delete to remove selected.",
        "folders_selected": "Selected {count} folders",
        "perform_iou_sweep_checkbox": "Perform IoU Sweep Evaluation (0.05-0.95)",
        "micro_batch_mode": "Micro Batch Mode",
        "micro_batch_size_label": "Chunk Size:",
        "micro_batch_tooltip": "Chunk bboxes to reduce CPU/GPU memory pressure (if you see DefaultCPUAllocator not enough memory, reduce chunk size).",
        "micro_batch_size_tooltip": "Number of bboxes per chunk (smaller = safer, larger = faster)",
        "dual_mode_eval_tooltip": "Run evaluation twice with/without small-colony filtering for comparison.",
        "fit_view": "Fit",
        "zoom_100": "100%",
        "show_labels": "Labels",
        "show_confidence": "Conf",
        "highlight_label": "Highlight:",
        "open_output_folder": "Open output folder",
        "copy_log": "Copy log",
        "clear_log": "Clear log",
        "help": "Help",
        "help_tooltip": "Open quick help (F1)",
    },
}


def get_ui_texts():
    return copy.deepcopy(_UI_TEXTS)
